### ISSUE TITLE
Docs: Installation procedure

### ISSUE THREAD

**Issue by vian21** [specs-feup/coral#2]
Hey,
I stumbled upon this paper over the summer and became really interested in this project. Could you provide some documentation on how to install Coral locally (deps included: clava-flow is not on npm) and how one could use it to check some C code?

Thank you. 

I believe this research has great potential. No need to invent a new language when you can just sanitize already battle tested code.

**Comment by Goncalerta** [comment]
Hello!

Thanks a lot for your interest. Right now, coral is still in a very early phase, and is not suitable for production scenarios. In the future, as we develop the tool, we will ease the instalation process and document all instructions.

If, however, you just want to experiment the tool as presented in the paper, here are the instructions for the latest version, corresponding to my [Msc thesis, published in july 2024](https://hdl.handle.net/10216/160536).

First, check if you have these pre-requisites installed:

- Node (v18)
- npm
- Java (JDK 17)
- Gradle
- Git


Create a new folder with the file `package.json`:

```json
{
  "name": "coraljs",
  "type": "module",
  "workspaces": [
    "clava/Clava-JS",
    "lara-framework/Lara-JS",
    "coral",
    "clava-flow"
  ]
}
```

Then run in that same folder:

```
git clone https://github.com/specs-feup/coral.git
cd coral
git checkout 202171be79a369be0eee6961e1952ce7ab4121b6
cd ..
git clone https://github.com/specs-feup/specs-java-libs
git clone https://github.com/specs-feup/lara-framework.git
cd lara-framework
git checkout 768af2dd4eb471a0ab7cc5b75be0bc33faa05330
cd ..
git clone https://github.com/specs-feup/clava.git
cd clava
git checkout f188b7d924b97bc0668e029e9af70cd942b61a80
cd ..
git clone https://github.com/specs-feup/clava-flow.git
cd clava-flow
git checkout a504de47349e525c778ccb34c14836a0cb9af7ae
cd ..
npm i
npm run build -w lara-framework/Lara-JS 
npm run build -w clava/Clava-JS
npm run build -w clava-flow
npm run build -w coral
npm i
cd clava/ClavaWeaver
gradle installDist
cd ../..
```

Finally, copy the folder `./clava/ClavaWeaver/build/install/ClavaWeaver` into a new folder called `java-binaries` in `./clava/Clava-JS`:

```
mkdir clava/Clava-JS/java-binaries
cp -r ./clava/ClavaWeaver/build/install/ClavaWeaver ./clava/Clava-JS/java-binaries
```

Now, to run the unit tests from the CORAL Benchmark:

```
npm run test -w coral
```

And to run on any files that you want, put those files inside the folder `./coral/in/sandbox` and run:

```
npm run sandbox -w coral
```

Note that several features are missing at this moment: do not use on files that deal with arrays or heap memory.

If you have any difficulty following these steps or any other question, please let me know! :)

**Comment by vian21** [comment]
Hey @Goncalerta 
Thank you for providing the steps. I tried them today and got this error log:
```bash
3042 info run java@0.14.0 install node_modules/java node-gyp rebuild
3043 info run java@0.14.0 install { code: 1, signal: null }
3044 verbose stack Error: command failed
3044 verbose stack     at promiseSpawn (/home/patrick/.config/nvm/versions/node/v22.6.0/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/lib/index.js:22:22)
3044 verbose stack     at spawnWithShell (/home/patrick/.config/nvm/versions/node/v22.6.0/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/lib/index.js:124:10)
3044 verbose stack     at promiseSpawn (/home/patrick/.config/nvm/versions/node/v22.6.0/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/lib/index.js:12:12)
3044 verbose stack     at runScriptPkg (/home/patrick/.config/nvm/versions/node/v22.6.0/lib/node_modules/npm/node_modules/@npmcli/run-script/lib/run-script-pkg.js:77:13)
3044 verbose stack     at runScript (/home/patrick/.config/nvm/versions/node/v22.6.0/lib/node_modules/npm/node_modules/@npmcli/run-script/lib/run-script.js:9:12)
3044 verbose stack     at /home/patrick/.config/nvm/versions/node/v22.6.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/rebuild.js:329:17
3044 verbose stack     at run (/home/patrick/.config/nvm/versions/node/v22.6.0/lib/node_modules/npm/node_modules/promise-call-limit/dist/commonjs/index.js:67:22)
3044 verbose stack     at /home/patrick/.config/nvm/versions/node/v22.6.0/lib/node_modules/npm/node_modules/promise-call-limit/dist/commonjs/index.js:84:9
3044 verbose stack     at new Promise (<anonymous>)
3044 verbose stack     at callLimit (/home/patrick/.config/nvm/versions/node/v22.6.0/lib/node_modules/npm/node_modules/promise-call-limit/dist/commonjs/index.js:35:69)
3045 verbose pkgid java@0.14.0
3046 error code 1
3047 error path /home/patrick/developer/safe-c/coraljs/node_modules/java
3048 error command failed
3049 error command sh -c node-gyp rebuild
3050 error gyp info it worked if it ends with ok
3050 error gyp info using node-gyp@10.2.0
3050 error gyp info using node@22.6.0 | linux | x64
3050 error gyp info find Python using Python version 3.12.3 found at "/usr/bin/python3"
3050 error gyp info spawn /usr/bin/python3
3050 error gyp info spawn args [
3050 error gyp info spawn args '/home/patrick/developer/safe-c/coraljs/node_modules/node-gyp/gyp/gyp_main.py',
3050 error gyp info spawn args 'binding.gyp',
3050 error gyp info spawn args '-f',
3050 error gyp info spawn args 'make',
3050 error gyp info spawn args '-I',
3050 error gyp info spawn args '/home/patrick/developer/safe-c/coraljs/node_modules/java/build/config.gypi',
3050 error gyp info spawn args '-I',
3050 error gyp info spawn args '/home/patrick/developer/safe-c/coraljs/node_modules/node-gyp/addon.gypi',
3050 error gyp info spawn args '-I',
3050 error gyp info spawn args '/home/patrick/.cache/node-gyp/22.6.0/include/node/common.gypi',
3050 error gyp info spawn args '-Dlibrary=shared_library',
3050 error gyp info spawn args '-Dvisibility=default',
3050 error gyp info spawn args '-Dnode_root_dir=/home/patrick/.cache/node-gyp/22.6.0',
3050 error gyp info spawn args '-Dnode_gyp_dir=/home/patrick/developer/safe-c/coraljs/node_modules/node-gyp',
3050 error gyp info spawn args '-Dnode_lib_file=/home/patrick/.cache/node-gyp/22.6.0/<(target_arch)/node.lib',
3050 error gyp info spawn args '-Dmodule_root_dir=/home/patrick/developer/safe-c/coraljs/node_modules/java',
3050 error gyp info spawn args '-Dnode_engine=v8',
3050 error gyp info spawn args '--depth=.',
3050 error gyp info spawn args '--no-parallel',
3050 error gyp info spawn args '--generator-output',
3050 error gyp info spawn args 'build',
3050 error gyp info spawn args '-Goutput_dir=.'
3050 error gyp info spawn args ]
3050 error gyp: Call to 'node findJavaHome.js' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
3050 error gyp ERR! configure error 
3050 error gyp ERR! stack Error: `gyp` failed with exit code: 1
3050 error gyp ERR! stack at ChildProcess.<anonymous> (/home/patrick/developer/safe-c/coraljs/node_modules/node-gyp/lib/configure.js:317:18)
3050 error gyp ERR! stack at ChildProcess.emit (node:events:520:28)
3050 error gyp ERR! stack at ChildProcess._handle.onexit (node:internal/child_process:294:12)
3050 error gyp ERR! System Linux 6.8.0-47-generic
3050 error gyp ERR! command "/home/patrick/.config/nvm/versions/node/v22.6.0/bin/node" "/home/patrick/developer/safe-c/coraljs/node_modules/.bin/node-gyp" "rebuild"
3050 error gyp ERR! cwd /home/patrick/developer/safe-c/coraljs/node_modules/java
3050 error gyp ERR! node -v v22.6.0
3050 error gyp ERR! node-gyp -v v10.2.0
3050 error gyp ERR! not ok
3051 silly unfinished npm timer reify 1729641740642
3052 silly unfinished npm timer reify:build 1729641751339
3053 silly unfinished npm timer build 1729641751340
3054 silly unfinished npm timer build:deps 1729641751341
3055 silly unfinished npm timer build:run:install 1729641751368
3056 silly unfinished npm timer build:run:install:node_modules/java 1729641751369
3057 verbose cwd /home/patrick/developer/safe-c/coraljs
3058 verbose os Linux 6.8.0-47-generic
3059 verbose node v22.6.0
3060 verbose npm  v10.8.2
3061 verbose exit 1
3062 verbose code 1

```

**Comment by Goncalerta** [comment]
It appears that it could not find JAVA_HOME. What do you get when you run `java --version`?
Can you confirm that you have java correctly installed and the JAVA_HOME environment variable properly set?

**Comment by vian21** [comment]
I do have hava installed but the `JAVA_HOME` env is not set on linux. I will fix. Great catch.
```sh
java --version
openjdk 21.0.4 2024-07-16
OpenJDK Runtime Environment (build 21.0.4+7-Ubuntu-1ubuntu224.04)
OpenJDK 64-Bit Server VM (build 21.0.4+7-Ubuntu-1ubuntu224.04, mixed mode, sharing)
```

**Comment by vian21** [comment]
I am no `gradle` expert. I tried debugging this but it seems that it is not allowing nested includes:
```sh
$ gradle installDist
openjdk version "21.0.4" 2024-07-16
OpenJDK Runtime Environment (build 21.0.4+7-Ubuntu-1ubuntu224.04)
OpenJDK 64-Bit Server VM (build 21.0.4+7-Ubuntu-1ubuntu224.04, mixed mode, sharing)

FAILURE: Build failed with an exception.

* Where:
Settings file 'coraljs/specs-java-libs/GsonPlus/settings.gradle' line: 3

* What went wrong:
A problem occurred evaluating settings 'GsonPlus'.
> Included build 'GsonPlus' cannot have included builds.
```

**Comment by vian21** [comment]
Found why. I was using Gradle version 4.4.1 which didn't not have all the functionalities needed. I used `sdkman` to install those specific versions.

### Prerequisites
- Node v18
- JDK 17
- gradle 7

It is all working fine. Thank you.

**Comment by Goncalerta** [comment]
Great! I'm very happy that it's working for you
Thank you for the heads-up on the gradle version! I will take it into account when I document the installation process.

**Comment by vian21** [comment]
To any one interested.

# Coral

Make C safe Again

### Prerequisites
- Node v18
- JDK 17
- grade 7

### Linux Installation
1. Install sdkman
```sh
curl -s "https://get.sdkman.io" | bash
```
2. Install JDK 17
```sh
sdk install java 17.0.12-jbr 
```
3. Install Grade 7
```sh
sdk use gradle 7.3 
```

```sh
git clone https://github.com/specs-feup/coral.git
cd coral
git checkout 202171be79a369be0eee6961e1952ce7ab4121b6
cd ..
git clone https://github.com/specs-feup/specs-java-libs
git clone https://github.com/specs-feup/lara-framework.git
cd lara-framework
git checkout 768af2dd4eb471a0ab7cc5b75be0bc33faa05330
cd ..
git clone https://github.com/specs-feup/clava.git
cd clava
git checkout f188b7d924b97bc0668e029e9af70cd942b61a80
cd ..
git clone https://github.com/specs-feup/clava-flow.git
cd clava-flow
git checkout a504de47349e525c778ccb34c14836a0cb9af7ae
cd ..
npm i
npm run build -w lara-framework/Lara-JS 
npm run build -w clava/Clava-JS
npm run build -w clava-flow
npm run build -w coral
npm i
cd clava/ClavaWeaver
gradle installDist
cd ../..
mkdir clava/Clava-JS/java-binaries
cp -r ./clava/ClavaWeaver/build/install/ClavaWeaver ./clava/Clava-JS/java-binaries
```

### Run benchmarks
```sh
npm run test -w coral
```

### Run custom programs
- Custom programs should be placed in `in/sandbox`
```sh
npm run sandbox -w coral
```
